
package webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://WebService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param mt
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionED")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionED", targetNamespace = "http://WebService/", className = "webservice.ConversionED")
    @ResponseWrapper(localName = "ConversionEDResponse", targetNamespace = "http://WebService/", className = "webservice.ConversionEDResponse")
    @Action(input = "http://WebService/BanqueService/ConversionEDRequest", output = "http://WebService/BanqueService/ConversionEDResponse")
    public double conversionED(
        @WebParam(name = "mt", targetNamespace = "")
        double mt);

    /**
     * 
     * @param code
     * @return
     *     returns webservice.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://WebService/", className = "webservice.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://WebService/", className = "webservice.GetCompteResponse")
    @Action(input = "http://WebService/BanqueService/getCompteRequest", output = "http://WebService/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @return
     *     returns java.util.List<webservice.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://WebService/", className = "webservice.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://WebService/", className = "webservice.GetComptesResponse")
    @Action(input = "http://WebService/BanqueService/getComptesRequest", output = "http://WebService/BanqueService/getComptesResponse")
    public List<Compte> getComptes();

}
